import { createClient } from '@/lib/supabase/server';
import { CURRENT_TERM, CURRENT_YEAR } from '@/lib/config';
import { processGradeData } from '@/lib/utils/processGradeData';
import { getPercentageColors } from '@/lib/utils/colors';

interface PublicLeaguePageProps {
  params: Promise<{
    token: string;
  }>;
}

export default async function PublicLeaguePage({ params }: PublicLeaguePageProps) {
  const { token } = await params;
  const supabase = await createClient();

  // 1. Look up token in grade_tokens
  const { data: tokenData, error: tokenError } = await supabase
    .from('grade_tokens')
    .select('*')
    .eq('token', token)
    .single();

  if (tokenError || !tokenData) {
    return (
      <div className="min-h-screen bg-gray-50 flex items-center justify-center p-4">
        <div className="bg-white rounded-xl shadow-lg border border-gray-200 p-8 max-w-md w-full text-center">
          <div className="w-12 h-12 bg-red-100 text-red-600 rounded-full flex items-center justify-center mx-auto mb-4 font-bold text-xl">
            !
          </div>
          <h1 className="text-2xl font-bold text-gray-900 mb-2">Invalid or Expired Link</h1>
          <p className="text-gray-600 text-sm mb-6">
            This physics league table link is invalid or has been regenerated by your teacher. Please request the latest link.
          </p>
          <div className="text-xs text-gray-400">Physics League Table • Read-only Access</div>
        </div>
      </div>
    );
  }

  const grade = tokenData.grade;

  // 2. Fetch students, academic_scores, and behavior_scores for this grade
  const [studentsRes, academicRes, behaviorRes] = await Promise.all([
    supabase
      .from('students')
      .select('*')
      .eq('grade', grade)
      .order('name'),
    supabase
      .from('academic_scores')
      .select('*')
      .eq('term', CURRENT_TERM)
      .eq('year', CURRENT_YEAR),
    supabase
      .from('behavior_scores')
      .select('*')
      .eq('term', CURRENT_TERM)
      .eq('year', CURRENT_YEAR),
  ]);

  const students = studentsRes.data ?? [];
  const academicScores = academicRes.data ?? [];
  const behaviorScores = behaviorRes.data ?? [];

  // 3. Process grade data
  const processedData = processGradeData(grade, students, academicScores, behaviorScores);

  return (
    <div className="min-h-screen bg-gray-50 text-gray-900 flex flex-col">
      {/* Header Banner */}
      <header className="bg-blue-900 text-white shadow-md">
        <div className="max-w-6xl mx-auto px-4 py-6 sm:px-6 flex flex-col sm:flex-row sm:items-center justify-between gap-4">
          <div>
            <h1 className="text-2xl sm:text-3xl font-extrabold tracking-tight">
              Grade {grade} Physics League Table
            </h1>
            <p className="text-blue-200 text-sm font-medium mt-1">
              {CURRENT_TERM}, {CURRENT_YEAR} • Public View
            </p>
          </div>
          <div className="inline-flex items-center px-3 py-1 rounded-full bg-blue-800/80 border border-blue-700 text-xs text-blue-100 font-semibold w-fit">
            🔒 Read-only view
          </div>
        </div>
      </header>

      {/* Main Content */}
      <main className="max-w-6xl mx-auto px-4 py-8 sm:px-6 flex-1 w-full space-y-8">
        {students.length === 0 ? (
          <div className="bg-white rounded-xl shadow p-8 text-center text-gray-500 font-medium border border-gray-200">
            No students found for Grade {grade}.
          </div>
        ) : (
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
            {/* Academic Performance Table */}
            <div className="bg-white rounded-xl shadow-sm border-2 border-gray-300 overflow-hidden flex flex-col">
              <div className="bg-gray-100 px-5 py-4 border-b border-gray-300">
                <h2 className="text-lg font-bold text-gray-900 flex items-center gap-2">
                  <span>🏆</span> Academic Performance
                </h2>
              </div>
              <div className="overflow-x-auto flex-1">
                <table className="w-full border-collapse">
                  <thead>
                    <tr className="bg-gray-50 border-b border-gray-300">
                      <th className="px-4 py-3 text-left text-xs font-bold text-gray-700 uppercase tracking-wider border-r border-gray-300 w-16">
                        Rank
                      </th>
                      <th className="px-4 py-3 text-left text-xs font-bold text-gray-700 uppercase tracking-wider border-r border-gray-300">
                        Student Name
                      </th>
                      <th className="px-4 py-3 text-right text-xs font-bold text-gray-700 uppercase tracking-wider w-32">
                        Weighted %
                      </th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-gray-300">
                    {processedData.rankedAcademic.map((item) => {
                      const { background, text } = getPercentageColors(
                        item.weightedPercentage,
                        item.hasData
                      );

                      return (
                        <tr key={item.student.id} className="hover:bg-gray-50/80 transition-colors">
                          <td className="px-4 py-3 text-sm font-bold text-gray-900 border-r border-gray-300">
                            {item.hasData && item.rank !== null ? item.rank : '—'}
                          </td>
                          <td className="px-4 py-3 text-sm font-semibold text-gray-900 border-r border-gray-300">
                            {item.student.name}
                          </td>
                          <td
                            className="px-4 py-3 text-sm text-right font-bold"
                            style={{ backgroundColor: background, color: text }}
                          >
                            {item.hasData ? `${item.weightedPercentage.toFixed(1)}%` : '—'}
                          </td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>
            </div>

            {/* Behavior Performance Table */}
            <div className="bg-white rounded-xl shadow-sm border-2 border-gray-300 overflow-hidden flex flex-col">
              <div className="bg-gray-100 px-5 py-4 border-b border-gray-300">
                <h2 className="text-lg font-bold text-gray-900 flex items-center gap-2">
                  <span>⭐</span> Behavior Performance
                </h2>
              </div>
              <div className="overflow-x-auto flex-1">
                <table className="w-full border-collapse">
                  <thead>
                    <tr className="bg-gray-50 border-b border-gray-300">
                      <th className="px-4 py-3 text-left text-xs font-bold text-gray-700 uppercase tracking-wider border-r border-gray-300 w-16">
                        Rank
                      </th>
                      <th className="px-4 py-3 text-left text-xs font-bold text-gray-700 uppercase tracking-wider border-r border-gray-300">
                        Student Name
                      </th>
                      <th className="px-4 py-3 text-right text-xs font-bold text-gray-700 uppercase tracking-wider w-36">
                        Behavior Avg
                      </th>
                    </tr>
                  </thead>
                  <tbody className="divide-y divide-gray-300">
                    {processedData.rankedBehavior.map((item) => {
                      const { background, text } = getPercentageColors(
                        item.average,
                        item.hasData
                      );

                      return (
                        <tr key={item.student.id} className="hover:bg-gray-50/80 transition-colors">
                          <td className="px-4 py-3 text-sm font-bold text-gray-900 border-r border-gray-300">
                            {item.hasData && item.rank !== null ? item.rank : '—'}
                          </td>
                          <td className="px-4 py-3 text-sm font-semibold text-gray-900 border-r border-gray-300">
                            {item.student.name}
                          </td>
                          <td
                            className="px-4 py-3 text-sm text-right font-bold"
                            style={{ backgroundColor: background, color: text }}
                          >
                            {item.hasData ? `${item.average.toFixed(1)}%` : '—'}
                          </td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        )}
      </main>

      {/* Subtle Footer */}
      <footer className="bg-white border-t border-gray-200 py-4 px-4 text-center text-xs text-gray-500 font-medium">
        Read-only student view • Physics League Table
      </footer>
    </div>
  );
}
